config/routes.rb
Rails.application.routes.draw do
  get '/restaurant_details', to: "restaurant_details#index"
  get '/results', to: "results#index"
  get '/search_conditions', to: "search_conditions#index"

  root "search_conditions#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/restaurant_details_controller.rb
require 'rexml/document'

class RestaurantDetailsController < ApplicationController
  def index
    @restaurant = Hash.new() # レストラン詳細情報を格納するハッシュ

    # uriの細分化、リクエストの送信
    uri_path = "https://webservice.recruit.co.jp/hotpepper/gourmet/v1/"
    uri_query = "?key=#{ENV['GOURMET_API_KEY']}&id=#{params[:id]}"
    parsed_uri = URI.parse(uri_path + uri_query)
    response = gourmet_api_request(parsed_uri)

    # XMLの解析、レストラン情報の格納
    doc = REXML::Document.new(response.body)
    REXML::XPath.match(doc, "/results/shop").map do |restaurant|
      @restaurant.store(:thumbnail_url, restaurant.elements["logo_image"].text)
      @restaurant.store(:name, restaurant.elements["name"].text)
      @restaurant.store(:address, restaurant.elements["address"].text)
      @restaurant.store(:open, restaurant.elements["open"].text)
    end

    p @restaurant
  end
end

app/controllers/results_controller.rb
require 'rexml/document'

class ResultsController < ApplicationController
  def index
    @restaurants = Array.new() # レストラン情報を格納する配列
    @radius = case params[:rad] # 半径の表示を変換
              when "1" then "300m"
              when "2" then "500m" 
              when "3" then "1.0km"
              when "4" then "2.0km"
              when "5" then "3.0km"
              else "Error"
              end

    # 環境変数が設定されていない場合はエラーを出す
    unless ENV['GOURMET_API_KEY'] then
      raise "GOURMET_API_KEY is not set"
    end

    # パラメータがない場合はトップページにリダイレクト
    unless params[:lat] && params[:lng] && params[:rad] then
      redirect_to root_path
    end

    # uriの細分化、リクエストの送信
    uri_path = "https://webservice.recruit.co.jp/hotpepper/gourmet/v1/"
    uri_query = "?key=#{ENV['GOURMET_API_KEY']}&lat=#{params[:lat]}&lng=#{params[:lng]}&range=#{params[:rad]}&count=100"
    parsed_uri = URI.parse(uri_path + uri_query)
    response = gourmet_api_request(parsed_uri)
    
    # XMLの解析、レストラン情報の格納
    doc = REXML::Document.new(response.body)
    REXML::XPath.match(doc, "/results/shop").map do |restaurant|
      restaurant_temp = Hash.new()
      restaurant_temp.store(:id, restaurant.elements["id"].text)
      restaurant_temp.store(:thumbnail_url, restaurant.elements["logo_image"].text)
      restaurant_temp.store(:name, restaurant.elements["name"].text)
      restaurant_temp.store(:address, restaurant.elements["address"].text)
      restaurant_temp.store(:access, restaurant.elements["access"].text)
      restaurant_temp.store(:mobile_access, restaurant.elements["mobile_access"].text)

      @restaurants << restaurant_temp
    end

    # ページネーション処理
    p @restaurants
    @paginatable_restaurants = Kaminari.paginate_array(@restaurants).page(params[:page]).per(10)
  end
end

app/controllers/search_conditions_controller.rb
class SearchConditionsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
require 'net/http'

module ApplicationHelper
  def gourmet_api_request(_parsed_uri)
    # Net::HTTP.newでHTTPのクライアントのオブジェクトを作成
    http = Net::HTTP.new(_parsed_uri.host, _parsed_uri.port)
    # HTTPでSSL/TLSを使うかどうかを設定する。
    http.use_ssl = true
    request = Net::HTTP::Get.new(_parsed_uri.request_uri)

    return http.request(request)
  end
end

app/helpers/restaurant_details_helper.rb
module RestaurantDetailsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/search_conditions_helper.rb
module SearchConditionsHelper
end

app/views/layouts/_header.html.erb
<header>
  <div class="logo_wrapper">
    <p id="logo">Restaurant Searcher</p>
  </div>
  <!-- google material icon -->
  <span class="material-symbols-outlined" id="restaurant_icon">
    restaurant
  </span>
</header>

app/views/layouts/_rails_default.html.erb
  <head>
    <title>restaurant researcher</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>

    <!-- setup google material icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=restaurant" />

    <!-- setup bootstrap -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/rails_default'%>
  <body>
    <%= render 'layouts/header'%>
    <%= yield %>

    <!--
    <%= debug(params) if Rails.env.development? %>]
    -->
  </body>
</html>

app/views/restaurant_details/index.html.erb
<div class="restaurant_details_main_content">
  <div class="restaurant_deatils_header">
    <%= link_to 'javascript:history.back()', class: "back_button_wrapper" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="back_arrow_icon" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5"/>
      </svg>
      <p class="back_button_text">検索結果に戻る</p>
    <% end %>
  </div>

  <div class="restaurant_details_content">
    <div class="restaurant_thumbnail_wrapper">
      <%= image_tag @restaurant[:thumbnail_url], class: "restaurant_thumbnail" %>
    </div>

    <div class="restaurant_info_field">
      <div class="restaurant_name_wrapper">
        <p class="restaurant_name">
          <%= @restaurant[:name] %>
        </p>
      </div>
      <div class="restaurant_open_wrapper">
        <p class="restaurant_open restaurant_open_index">営業時間</p>
        <p class="restaurant_open">
          <%= @restaurant[:open] %>
        </p>
      </div>
      <div class="restaurant_address_wrapper">
        <p class="restaurant_address restaurant_address_index ">住所</p>
        <p class="restaurant_address">
          <%= @restaurant[:address] %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/results/index.html.erb
<div class="results_main_content">
  <div class="results_header">
    <p class="results_header_text">検索結果 (<%= @radius %>)</p>

  
    <%= link_to search_conditions_path do %>
      <div class="button">
        <span>再検索</span>
      </div>
    <% end %>
  </div>

  <ul class="results_list">
    <div class="pagination_wrapper">
      <%= paginate @paginatable_restaurants %>
    </div>

    <% @paginatable_restaurants.each do |restaurant| %>
      <%= link_to "#{restaurant_details_path}/?id=#{restaurant[:id]}", class: "restaurant_card_button" do %>
        <li>
          <div class="restaurant_card">
            <div class="thumbnail_wrapper">
              <%= image_tag restaurant[:thumbnail_url], class: "thumbnail"%>
            </div>
            <div class="restaurant_info">
              <div class="restaurant_name">
                <p class="restaurant_name_text"><%= restaurant[:name] %></p>
              </div>
              <div class="restaurant_address">
                <p class="restaurant_address_text"><%= restaurant[:address] %></p>
              </div>
              <div class="restaurant_access">
                <p class="restaurant_access_text mobile"><%= restaurant[:mobile_access] %></p>
                <p class="restaurant_access_text pc"><%= restaurant[:access] %></p>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    <% end %>

    <div class="pagination_wrapper">
      <%= paginate @paginatable_restaurants %>
    </div>
  </ul>
</div>

app/views/search_conditions/index.html.erb
<div class="search_condition_main_content">  
  <div class="search_card">

    <div class="card_header">
      <p class="header_text">サーチステータス</p>
    </div>

    <div class="card_body">
      
      <div class="location_status">
        <p class="card_text">現在地の取得・・・</p>
        <div class="dialog" data-controller="geolocation">

          <div class="spinner-border dialog_icon" role="status" data-geolocation-target="slide">
            <span class="visually-hidden">Loading...</span>
          </div>
          <div data-geolocation-target="slide">
            <svg xmlns="http://www.w3.org/2000/svg" class="dialog_icon check_icon" fill="currentColor" viewBox="0 0 16 16">
              <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425z"/>
            </svg>
          </div>

        </div>
      </div>

      <label for="radius_range" class="form-label">
        <p class="card_text">現在地からの検索半径</p>
      </label>

      <div class="range_wrapper">
        <input 
          type="range" class="form-range distance_range" min="1" max="5" 
          id="radius_range" oninput="updateDistanceValue(this.value)"
        >
        <input
          type="text" id="distance_display" class="distance_text"
          readonly value="1000m"
        >
      </div>
      <div class="search_button_wrapper" data-controller="geolocation">
        <button class="button" data-action="geolocation#search">検索する</button>
      </div>
    </div>
  </div>
</div>